import type { Metadata } from "next";

import NextAuthSessionProvider from "@/providers/sessionProvider";
import { NavBar } from "@/components/NavBar";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen">
        <NextAuthSessionProvider>
          <NavBar />
          <div className="flex flex-col items-center justify-center p-24">
            {children}
          </div>
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
